version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
  app:
    image: todo-api
    ports:
      - 3000:3000
